# Generated by Django 3.2.8 on 2023-01-10 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EnvironmentalInformation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(max_length=40, null=True, verbose_name='年级')),
                ('Major', models.CharField(max_length=40, null=True, verbose_name='专业')),
                ('Class', models.CharField(max_length=40, null=True, verbose_name='班号')),
                ('Others', models.CharField(max_length=40, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '班级管理',
                'verbose_name_plural': '班级管理',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.PositiveIntegerField(verbose_name='成绩')),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneralInformation.classmanagement', verbose_name='所属班级')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='CourseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(default='课时名称', max_length=40, verbose_name='课时名称')),
                ('CourseContent', models.CharField(max_length=50, null=True, verbose_name='课程要求')),
                ('CourseStartTime', models.DateTimeField(verbose_name='课程开始时间')),
                ('CourseStopTime', models.DateTimeField(verbose_name='课程结束时间')),
                ('TemplateOfExperimentReport', models.FileField(blank=True, max_length=300, upload_to='static/Upload/TemplateOfExperimentReport', verbose_name='实验报告模板文件')),
                ('Experiments', models.ManyToManyField(to='EnvironmentalInformation.Experiments', verbose_name='课时包含的实验环境')),
                ('JoinUsers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='参加课程的用户')),
            ],
            options={
                'verbose_name': '课时管理',
                'verbose_name_plural': '课时管理',
            },
        ),
    ]
