# Generated by Django 3.2.8 on 2023-01-11 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnvironmentalInformation', '0002_delete_containermanagement'),
        ('GeneralInformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerName', models.CharField(max_length=40, verbose_name='容器名称')),
                ('ContainerPorts', models.CharField(max_length=30, verbose_name='容器端口映射')),
                ('ContainerStartTime', models.DateTimeField(verbose_name='容器启动时间')),
                ('ContainerCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralInformation.coursemanagement', verbose_name='容器归属课程')),
                ('ContainerImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnvironmentalInformation.experiments', verbose_name='容器基于的Image')),
                ('ContainerUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='启动容器的用户')),
            ],
            options={
                'verbose_name': '实验容器管理',
                'verbose_name_plural': '实验容器管理',
            },
        ),
    ]
