# Generated by Django 3.2.8 on 2023-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralInformation', '0002_containermanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='containermanagement',
            name='ContainerCode',
            field=models.CharField(max_length=40, null=True, verbose_name='容器Hash编码'),
        ),
        migrations.AlterField(
            model_name='containermanagement',
            name='ContainerName',
            field=models.CharField(max_length=40, null=True, verbose_name='容器名称'),
        ),
    ]
