# Generated by Django 3.2.8 on 2023-04-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralInformation', '0004_experimentalreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containermanagement',
            options={'verbose_name': '实验容器', 'verbose_name_plural': '实验容器'},
        ),
    ]
