# Generated by Django 3.2.8 on 2023-01-10 03:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuidanceName', models.CharField(default='实验指导书名称', max_length=40, verbose_name='实验指导书名称')),
                ('GuidanceContent', ckeditor.fields.RichTextField(verbose_name='实验指导书内容')),
            ],
            options={
                'verbose_name': '实验指导',
                'verbose_name_plural': '实验指导书',
            },
        ),
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExperimentName', models.CharField(default='环境名称', max_length=40, verbose_name='环境名称')),
                ('ExperimentInformation', models.CharField(default='环境简介', max_length=40, verbose_name='环境简介')),
                ('ExperimentImage', models.CharField(default='实验环境Image', max_length=100, verbose_name='实验环境Image')),
                ('ExperimentPorts', models.CharField(default='实验环境服务端口信息，多个端口请使用空格分隔', max_length=30, verbose_name='实验环境映射端口')),
                ('ExperimentGuidance', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnvironmentalInformation.guidances', verbose_name='实验指导书')),
            ],
            options={
                'verbose_name': '实验基础环境',
                'verbose_name_plural': '实验基础环境',
            },
        ),
        migrations.CreateModel(
            name='ContainerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerName', models.CharField(max_length=40, verbose_name='容器名称')),
                ('ContainerPorts', models.CharField(max_length=30, verbose_name='容器端口映射')),
                ('ContainerStartTime', models.DateTimeField(verbose_name='容器启动时间')),
                ('ContainerImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnvironmentalInformation.experiments', verbose_name='容器基于的Image')),
                ('ContainerUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='启动容器的用户')),
            ],
            options={
                'verbose_name': '实验容器管理',
                'verbose_name_plural': '实验容器管理',
            },
        ),
    ]
