# Generated by Django 3.2.8 on 2023-01-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvironmentalInformation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContainerManagement',
        ),
    ]
