# Generated by Django 3.2.8 on 2023-01-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogoFile', models.FileField(max_length=300, null=True, upload_to='static/', verbose_name='系统Logo图片')),
            ],
            options={
                'verbose_name': 'Logo管理',
                'verbose_name_plural': 'Logo管理',
            },
        ),
    ]
