# Generated by Django 3.2.8 on 2023-01-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemSettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogoFile', models.FileField(max_length=300, null=True, upload_to='static/', verbose_name='系统Logo图片')),
                ('IPRangeStart', models.IntegerField(verbose_name='生成容器端口开始')),
                ('IPRangeStop', models.IntegerField(verbose_name='生成容器端口截至')),
            ],
            options={
                'verbose_name': 'Logo管理',
                'verbose_name_plural': 'Logo管理',
            },
        ),
        migrations.DeleteModel(
            name='SystemLogoSetting',
        ),
    ]
