# Generated by Django 3.2.8 on 2023-01-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SystemSettings', '0003_auto_20230112_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': '系统设置', 'verbose_name_plural': '系统设置'},
        ),
    ]
